### ISSUE TITLE
Best practices link 404s

### ISSUE THREAD

**Issue by emilyselwood** [stac-utils/stac-rs#169]
In the spec examples readme.md the best practices link goes to a repo local file that doesn't exist.

https://github.com/gadomski/stac-rs/blob/main/spec-examples/v1.0.0/README.md

**Comment by emilyselwood** [comment]
Having gone through and checked a number of the other links on that page quite a lot of them don't work. Looks like anything that is not pointing at a .json file isn't working. Was this part of the repo cloned from somewhere else?

**Comment by gadomski** [comment]
Yes, the spec examples were copied from https://github.com/radiantearth/stac-spec/tree/master/examples. I should remove the README from this repo, because as you point out, it's broken. Thanks for the note!
