### ISSUE TITLE
Add tracing to server, and maybe other crates

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stac-rs#315]

**Comment by johnnylarner** [comment]
Would be interested in taking this on if you had some more specific reqs

**Comment by gadomski** [comment]
I don't have any specifics — I created this issue when doing some rough benchmarking for a talk. I do think folks would like to be able to log **stac-server** requests, so at minimum maybe just instrumenting the functions in https://github.com/stac-utils/stac-rs/blob/main/server/src/routes.rs and then adding some light documentation on how to use the tracing?
