### ISSUE TITLE
Extend PgStac backend to accept generic pool types

### ISSUE THREAD

**Issue by johnnylarner** [stac-utils/stac-rs#375]
Hey,
We are using `stac-rs` tooling in production (and are pretty satisfied). We've found a restriction on using the `PgStac` backend which is that the `pool` type *requires* an unencrypted connection. See [this line](https://github.com/stac-utils/stac-rs/blob/5e3bece004c13a6697972f8a9e56e3f7814a10e7/server/src/backend/pgstac.rs#L13).

To get around this, we used the same approach as the `sqlx` library to implement an unverified TLS connection. We think this is a more suitable default for a Postgres connection as often Postgres is setup by default to reject connections that don't use TLS, verified or not.

I'd be more than happy to contribute this as a short PR.

**Comment by gadomski** [comment]
@johnnylarner released v0.3.0 of **stac-server**: https://crates.io/crates/stac-server/0.3.0. I didn't release the CLI, but if you're using that as well, I can cut a pre-release of that (there's a lot of churn in the core crate right now so I'm not quite ready for a full release of the CLI).

**Comment by johnnylarner** [comment]
Amazing, we'll integrate the changes this week
