### ISSUE TITLE
Handling of default-members field in Cargo.toml

### ISSUE THREAD

**Issue by weiji14** [stac-utils/stac-rs#527]
Hi @gadomski,

I'm working on packaging [stacrs on PyPI](https://pypi.org/project/stacrs/0.2.2) for conda-forge, and am encountering an issue when running [cargo-bundle-licenses](https://github.com/sstadick/cargo-bundle-licenses) (see details at https://github.com/conda-forge/staged-recipes/pull/28293#issuecomment-2489661805). It seems that what is packaged in the sdist ("crates/api", "crates/core", "crates/extensions") is less than what is listed under [`default-members`](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-default-members-field) field

Specifically, here's what's in the Cargo.toml file:

Version from tag `python-v0.2.2`:

https://github.com/stac-utils/stac-rs/blob/d13c0f474c1e3b2fc3854bdf60f10608b273c689/Cargo.toml#L13-L18

More recent version on main, commit bc62c87820899fc72e5d56d460a3c7182ef43d02 has more than four:

https://github.com/stac-utils/stac-rs/blob/bc62c87820899fc72e5d56d460a3c7182ef43d02/Cargo.toml#L15-L22

I'm aware that `crates/cli` is separately packaged at https://pypi.org/project/stacrs-cli/, so it probably won't make sense to include `crates/cli` in the `stacrs` PyPI package. Not sure if it would be ok to remove `crate/cli` from default-members, or if this would need to be handled on maturin itself (https://github.com/PyO3/maturin/issues/2046)?

**Comment by gadomski** [comment]
🤔 thanks for flagging @weiji14. It looks like it should be as simple as removing `extensions` and `cli` from `default-members`, but that feels awkward — I should be able to have whatever I want in my workspace-level `Cargo.toml` and not worry about what **maturin** thinks.

There's a couple of other slightly-awkward things about including **stacrs** (Python) in the same monorepo as all the Rust crates — e.g. as currently configured, I can release a new **stacrs** version from unreleased Rust code. That was nice during active development, but now that folks are Actually Using **stacrs** I think should tighten things up.

All that to say, I think I'm going to move **stacrs** to its own repo and release v0.2.3 from there, which should clean up your issue (and many others). Standby.

**Comment by gadomski** [comment]
@weiji14 just released https://pypi.org/project/stacrs/0.3.0/, and was able to build from the sdist, so hopefully you're good to go 🤞🏼. Please re-open if that's not the case!

**Comment by weiji14** [comment]
Yep, the initial issue with `cargo-bundle-licenses` appears to be gone now with `stacrs=0.3.0`. Thanks for migrating all the code over to https://github.com/gadomski/stacrs!

There's still some build errors I need to fix at https://github.com/conda-forge/staged-recipes/pull/28293, but they seem to be related to compiling libduckdb-sys, so I'll try and figure that out separately.
